proxy:
  service:
    type: ClusterIP # TODO: Change to ClusterIP w/ Route?
  # https:  # TODO: enable in future
  #   enabled: true
  #   type: letsencrypt
  #   hosts:
  #     - local.jovyan.org
  #   letsencrypt:
  #     contactEmail: "jovyan@jupyter.test"
  #     acmeServer: https://pebble/dir
  traefik:
    # TODO: Check if a RH UBI:8 image exists for traefik already client side.
    containerSecurityContext: &security_context
      runAsUser: 1000670008 # nobody user
      runAsGroup: 65534 # nobody group
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
  secretSync:
    image:
      name: willhgemba/secret-sync
      tag: latest
    containerSecurityContext:
      <<: *security_context
      runAsUser: 1000670009 # nobody user
      runAsGroup: 65534 # nobody group
  chp:
    image:
      name: willhgemba/configurable-http-proxy
      tag: latest
    containerSecurityContext:
      <<: *security_context
      runAsUser: 1000670007 # nobody user
      runAsGroup: 65534 # nobody group

hub:
  image:
    name: willhgemba/hub
    tag: latest
  podSecurityContext:
    fsGroup:
  containerSecurityContext:
    <<: *security_context
    runAsUser: 1000670006
    runAsGroup: 2000
  livenessProbe:
    # The livenessProbe's aim to give JupyterHub sufficient time to startup but
    # be able to restart if it becomes unresponsive for ~5 min.
    enabled: false
    initialDelaySeconds: 300
    periodSeconds: 10
    failureThreshold: 30
    timeoutSeconds: 3
  readinessProbe:
    # The readinessProbe's aim is to provide a successful startup indication,
    # but following that never become unready before its livenessProbe fail and
    # restarts it if needed. To become unready following startup serves no
    # purpose as there are no other pod to fallback to in our non-HA deployment.
    enabled: false
    initialDelaySeconds: 0
    periodSeconds: 2
    failureThreshold: 1000
    timeoutSeconds: 1

singleuser:
  startTimeout: 1200 # Extend because of large image size.
  networkTools:
    image:
      name: willhgemba/network-tools
      tag: latest
  image:
    name: willhgemba/scipy-notebook # base-notebook
    tag: "latest"
  uid: 1000679998
  fsGid:
  cloudMetadata:
    blockWithIptables: false

prePuller:
  containerSecurityContext:
    <<: *security_context
    runAsUser: 1000670003 # nobody user
    runAsGroup: 1000670000 # nobody group
  hook:
    image:
      name: willhgemba/image-awaiter
      tag: latest
    enabled: true
    containerSecurityContext:
      <<: *security_context
      runAsUser: 1000670004 # nobody user
      runAsGroup: 1000670000 # nobody group
  pause:
    containerSecurityContext:
      <<: *security_context
      runAsUser: 1000671004
      runAsGroup: 1000671004

scheduling:
  userScheduler:
    containerSecurityContext:
      <<: *security_context
      runAsUser: 1000670001
      runAsGroup: 65534
    enabled: true
    replicas: 2
    # Can be set too low too not show scoring of scheduled pods, but also too
    # high to show hex dumps of all network traffic.
    #
    # FIXME: Tweak this to include scoring, but exclude hex dumps. 10 includes
    #        hex dumps. 4 does not include scoring. Trying with 6...
    logLevel: 6 # 4 by default, 6 for local dev.
  podPriority:
    enabled: true

debug:
  enabled: true
