proxy:
  service:
    type: ClusterIP # TODO: Change to ClusterIP w/ Route?
  # https:  # TODO: enable in future
  #   enabled: true
  #   type: letsencrypt
  #   hosts:
  #     - local.jovyan.org
  #   letsencrypt:
  #     contactEmail: "jovyan@jupyter.test"
  #     acmeServer: https://pebble/dir
  traefik:
    # TODO: Check if a RH UBI:8 image exists for traefik already client side.
    containerSecurityContext: &security_context
      runAsUser: 1000660008 # nobody user
      runAsGroup: 65534 # nobody group
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
  secretSync:
    image:
      name: willhgemba/secret-sync
      tag: latest
    containerSecurityContext:
      <<: *security_context
      runAsUser: 1000660009 # nobody user
      runAsGroup: 65534 # nobody group
  chp:
    image:
      name: willhgemba/configurable-http-proxy
      tag: latest
    containerSecurityContext:
      <<: *security_context
      runAsUser: 1000660007 # nobody user
      runAsGroup: 65534 # nobody group

hub:
  image:
    name: willhgemba/hub
    tag: latest
  podSecurityContext:
    fsGroup:
  containerSecurityContext:
    <<: *security_context
    runAsUser: 1000660006
    runAsGroup: 2000

singleuser:
  startTimeout: 1200 # Extend because of large image size.
  networkTools:
    image:
      name: willhgemba/network-tools
      tag: latest
  image:
    name: willhgemba/scipy-notebook # base-notebook
    tag: "latest"
  uid: 1000669998
  fsGid:
  cloudMetadata:
    blockWithIptables: false

prePuller:
  containerSecurityContext:
    <<: *security_context
    runAsUser: 1000660003 # nobody user
    runAsGroup: 1000660000 # nobody group
  hook:
    image:
      name: willhgemba/image-awaiter
      tag: latest
    enabled: true
    containerSecurityContext:
      <<: *security_context
      runAsUser: 1000660004 # nobody user
      runAsGroup: 1000660000 # nobody group
  pause:
    containerSecurityContext:
      <<: *security_context
      runAsUser: 1000661004
      runAsGroup: 1000661004

scheduling:
  userScheduler:
    containerSecurityContext:
      <<: *security_context
      runAsUser: 1000660001
      runAsGroup: 65534
    enabled: true
    replicas: 2
    # Can be set too low too not show scoring of scheduled pods, but also too
    # high to show hex dumps of all network traffic.
    #
    # FIXME: Tweak this to include scoring, but exclude hex dumps. 10 includes
    #        hex dumps. 4 does not include scoring. Trying with 6...
    logLevel: 6 # 4 by default, 6 for local dev.
  podPriority:
    enabled: true

debug:
  enabled: true
