resources:
  - ../base
  - resource-route-proxy-public.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: hub
    behavior: merge
    files:
      - jupyterhub_config.py
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: proxy
    path: patch-proxy-np.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: hub
    path: patch-hub-np.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: singleuser
    path: patch-singleuser-np.yaml
